/**
 * @file imu.h
 *
 * @brief Inertial Measurement Unit
 *
 * This is to separate code generated by the CubeMX
 *
 * Copyright © 2017 Oleksii Aliakin. All rights reserved.
 * Author: Oleksii Aliakin (alex@nls.la)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SINS_IMU_H
#define SINS_IMU_H

#include "stm32l476g_discovery_gyroscope.h"

#include <mavlink.h>

HAL_StatusTypeDef imu_init();

int imu_read(mavlink_raw_imu_t *imu_data);

#endif  // SINS_IMU_H
