/**
 * @file imu.c
 *
 * @brief Inertial Measurement Unit
 *
 * This is to separate code generated by the CubeMX
 *
 * Copyright © 2017 Oleksii Aliakin. All rights reserved.
 * Author: Oleksii Aliakin (alex@nls.la)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "imu.h"

static const float ROLL_COMPENSATION = -4.0;
static const float PITCH_COMPENSATION = 4.0;
static const float YAW_COMPENSATION = -0.2;
static float buffer[3] = { 0 };
static uint32_t prevTick = 0;

float runge_kutta(const float h, const float val)
{
    const float k1 = h * val;
    const float k2 = h * val + k1 / 2;
    const float k3 = h * val + k2 / 2;
    const float k4 = h * val + k3;
    const float d = (k1 + 2 * k2 + 2 * k3 + k4) / 6;
    return d;
}

HAL_StatusTypeDef imu_init()
{
    HAL_StatusTypeDef result = HAL_OK;

    if (BSP_GYRO_Init() != HAL_OK) {
        BSP_LED_On(LED_RED);  // TODO: better error reporting
        result = HAL_ERROR;
    }
    return result;
}

int imu_read(mavlink_attitude_t *imu_data)
{
    BSP_GYRO_GetXYZ(buffer);

    uint32_t currentTick = HAL_GetTick();
    uint32_t millisElapsed = currentTick - prevTick;
    prevTick = currentTick;

    imu_data->time_boot_ms = currentTick;

    imu_data->rollspeed = buffer[0] / 1000.0 + ROLL_COMPENSATION;
    imu_data->pitchspeed = buffer[1] / 1000.0 + PITCH_COMPENSATION;
    imu_data->yawspeed = buffer[2] / 1000.0 + YAW_COMPENSATION;

    imu_data->roll += runge_kutta(millisElapsed / 1000.0, imu_data->rollspeed);
    imu_data->pitch += runge_kutta(millisElapsed / 1000.0, imu_data->pitchspeed);
    imu_data->yaw += runge_kutta(millisElapsed / 1000.0, imu_data->yawspeed);

    return true;
}
