/**
 * @file main.c
 *
 * @brief Declaration of main functions
 *
 * This is to separate code generated by the CubeMX
 *
 * Copyright © 2017 Oleksii Aliakin. All rights reserved.
 * Author: Oleksii Aliakin (alex@nls.la)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "main_impl.h"
#include "stm32l476g_discovery.h"

#include "stm32l4xx_hal_uart.h"

//sudo rfcomm connect 0 98:D3:32:70:5C:11 1

extern UART_HandleTypeDef huart1;

char *buff = "Hello\n\r";

void main_init()
{
    BSP_LED_Init(LED_RED);
    BSP_LED_Init(LED_GREEN);

    BSP_LED_On(LED_RED);
    BSP_LED_Off(LED_GREEN);
}

void main_loop_step()
{
    HAL_UART_Transmit(&huart1, (uint8_t*)buff, 8, 5);
    BSP_LED_Toggle(LED_RED);
    BSP_LED_Toggle(LED_GREEN);
    HAL_Delay(2000);
}
