/**
 * @file main.h
 *
 * @brief Declaration of main functions
 *
 * This is to separate code generated by the CubeMX
 *
 * Copyright © 2017 Oleksii Aliakin. All rights reserved.
 * Author: Oleksii Aliakin (alex@nls.la)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SINS_MAIN_IMPL_H
#define SINS_MAIN_IMPL_H

#include "main.h"

/**
 * @brief Called from the main() function
 */
void main_init();

/**
 * @brief Called from the main infinite loop
 */
void main_loop_step();

#endif // SINS_MAIN_IMPL_H
